export const GET_ALLCOINS_REQUEST = "DGET_COINS_REQUEST";
export const GET_ALLCOINS_SUCCESS = "GET_COINS_SUCCESS";
export const GET_ALLCOINS_FAILURE = "GET_COINS_FAILURE";

export const CURRENT_RATES_REQUEST = "CURRENT_RATES_REQUEST";
export const CURRENT_RATES_SUCCESS = "CURRENT_RATES_SUCCESS";
export const CURRENT_RATES_FAILURE = "CURRENT_RATES_FAILURE";
