export const DEPOSITFUND_DETAILS_REQUEST = "DEPOSITFUND_DETAILS_REQUEST";
export const DEPOSITFUND_DETAILS_SUCCESS = "DEPOSITFUND_DETAILS_SUCCESS";
export const DEPOSITFUND_DETAILS_FAILURE = "DEPOSITFUND_DETAILS_FAILURE";
