"use client";

export const GET_UPI_ADDRESS_REQUEST = "DEPOSITFUND_DETAILS_REQUEST";
export const GET_UPI_ADDRESS_SUCCESS = "DEPOSITFUND_DETAILS_SUCCESS";
export const GET_UPI_ADDRESS_FAILURE = "DEPOSITFUND_DETAILS_FAILURE";

export const GET_MANUAL_ACCOUNT_REQUEST = "GET_MANUAL_ACCOUNT_REQUEST";
export const GET_MANUAL_ACCOUNT_SUCCESS = "GET_MANUAL_ACCOUNT_SUCCESS";
export const GET_MANUAL_ACCOUNT_FAILURE = "GET_MANUAL_ACCOUNT_FAILURE";


export const GET_USE_VAN_REQUEST = "GET_USE_VAN_REQUEST";
export const GET_USE_VAN_SUCCESS = "GET_USE_VAN_SUCCESS";
export const GET_USE_VAN_FAILURE = "GET_USE_VAN_FAILURE";





