import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "BIT24HR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-primary">
      <body className="font-poppinsRegular">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
